In [2]:
import numpy as np

In [4]:
weight = np.random.normal(0, 0.0030, [10, 1])
print(weight)

[[-0.00051431]
 [-0.00145973]
 [ 0.00258863]
 [-0.00281518]
 [ 0.00292126]
 [ 0.00419086]
 [-0.0066754 ]
 [ 0.00158877]
 [ 0.00356048]
 [ 0.00329027]]


In [45]:
data = np.zeros([5, 10])
print(data)
print(data.shape[0])

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
5


In [5]:
shuffle_map = np.arange(10)

In [6]:
shuffle_map

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.random.shuffle(shuffle_map)

In [8]:
shuffle_map

array([6, 3, 5, 1, 2, 8, 7, 4, 0, 9])

In [9]:
mb_size = 2
step_count = int(10 * 0.8) // mb_size
test_begin_idx = step_count * mb_size

In [11]:
test_begin_idx

8

In [17]:
shuffle_map[test_begin_idx:]

0